---
version: '3'
services:
  girder:
    environment:
      DSA_PROVISION_YAML: ${DSA_PROVISION_YAML:-/opt/digital_slide_archive/devops/dsa/provision.yaml}
    volumes:
      - ./provision.local.yaml:/opt/digital_slide_archive/devops/dsa/provision.yaml
      - /home/aza4423/dsa/wsi-superpixel-guided-labeling:/opt/wsi-superpixel-guided-labeling
